### ISSUE TITLE
Input type (double) and bias type (float) should be the same

### ISSUE THREAD

**Issue by InspectaGadget** [ClownsharkBatwing/RES4LYF#22]
Hi ! 

I really feel silly, sorry to bother : 
I just tried to use clownshaksampler, and every setting i set i got this issue : Input type (double) and bias type (float) should be the same

And feel like i get errors i don't get usually, like  "clip missing: ['text_projection.weight']" , 

2024-12-14T19:00:58.787375 - got prompt
2024-12-14T19:00:58.857125 - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-12-14T19:00:58.857125 - model_type FLUX
2024-12-14T19:01:23.610721 - clip missing: ['text_projection.weight']
2024-12-14T19:01:26.621545 - Using pytorch attention in VAE
2024-12-14T19:01:26.625551 - Using pytorch attention in VAE
2024-12-14T19:01:26.941230 - Requested to load FluxClipModel_
2024-12-14T19:01:29.125183 - loaded completely 9.5367431640625e+25 9319.23095703125 True
2024-12-14T19:01:29.493527 - Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-12-14T19:01:29.513071 - Requested to load Flux
2024-12-14T19:01:37.233893 - loaded partially 9436.11572427368 9436.005859375 202
2024-12-14T19:01:40.970051 - 
  0%|                                                                                           | 0/40 [00:03<?, ?it/s]2024-12-14T19:01:40.970051 - 
2024-12-14T19:01:40.980074 - !!! Exception during processing !!! Input type (double) and bias type (float) should be the same
2024-12-14T19:01:40.980074 - Traceback (most recent call last):
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\samplers.py", line 526, in main
    return SharkSampler().main(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\samplers.py", line 276, in main
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, x.clone(), noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 48, in sample_custom
    samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 135, in sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 911, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 897, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 866, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 850, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 100, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 707, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\rk_sampler.py", line 343, in sample_rk
    callback({'x': x, 'i': step, 'sigma': sigma, 'sigma_next': sigma_next, 'denoised': data_[0]}) if callback is not None else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 705, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\latent_preview.py", line 102, in callback
    preview_bytes = previewer.decode_latent_to_preview_image(preview_format, x0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\latent_preview.py", line 24, in decode_latent_to_preview_image
    preview_image = self.decode_latent_to_preview(x0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\latent_preview.py", line 32, in decode_latent_to_preview
    x_sample = self.taesd.decode(x0[:1])[0].movedim(0, 2)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\taesd\taesd.py", line 74, in decode
    x_sample = self.taesd_decoder((x - self.vae_shift) * self.vae_scale)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 98, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Evolut\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: Input type (double) and bias type (float) should be the same

2024-12-14T19:01:40.984080 - Prompt executed in 42.19 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":525,"last_link_id":1324,"nodes":[{"id":285,"type":"VAEDecode","pos":[590,-420],"size":[210,46],"flags":{},"order":6,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":1268},{"name":"vae","type":"VAE","link":1280}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[594],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":284,"type":"SaveImage","pos":[591,-314],"size":[730.3121337890625,745.936279296875],"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":594}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":518,"type":"FluxGuidance","pos":[-20,-310],"size":[211.60000610351562,58],"flags":{},"order":4,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":1299}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[1300],"slot_index":0}],"properties":{"Node name for S&R":"FluxGuidance"},"widgets_values":[3.5]},{"id":524,"type":"EmptySD3LatentImage","pos":[-251,-360],"size":[210,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[1321],"slot_index":0}],"properties":{"Node name for S&R":"EmptySD3LatentImage"},"widgets_values":[1024,1024,1]},{"id":514,"type":"CLIPTextEncode","pos":[-215,-199],"size":[406.8311767578125,402.38238525390625],"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":1291}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[1299],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["Cold war photo, rows of uniform brown brick townhouses line both sides of a narrow residential street. The houses, with their tall rectangular windows and minimal decorative features, reflect a post-war architectural style, functional and sturdy. Many windows show reflections of overcast clouds, while others have sheer curtains drawn halfway, revealing a dimly lit interior. Small snow patches cling to the ground near the curbs, and frost lines are visible on the pavement, suggesting the remnants of a recent snowfall. Sparse, leafless trees stand along the sidewalk, their thin branches reaching upwards, casting faint shadows on the buildings. Streetlights with black, curved poles appear evenly spaced, their frosted glass shades slightly foggy, though not illuminated.\n\nCloser to the center of the frame, a military tank sits on the damp asphalt, its olive-green paint matte and weathered, with faint chips exposing bare metal at the edges. The tank’s turret is angled slightly to the side, and a small red star emblem near its front adds a stark, minimalistic detail. The tank is offset, its position making the street feel wider and more foreboding.",[false,true]]},{"id":508,"type":"ClownsharKSampler","pos":[219,-310],"size":[322.40692138671875,868],"flags":{},"order":5,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1324},{"name":"positive","type":"CONDITIONING","link":1300,"shape":7},{"name":"negative","type":"CONDITIONING","link":null,"shape":7},{"name":"sigmas","type":"SIGMAS","link":null,"shape":7},{"name":"latent_image","type":"LATENT","link":1321,"shape":7},{"name":"guides","type":"GUIDES","link":null,"shape":7},{"name":"options","type":"OPTIONS","link":null,"shape":7},{"name":"automation","type":"AUTOMATION","link":null,"shape":7}],"outputs":[{"name":"output","type":"LATENT","links":[1268],"slot_index":0},{"name":"denoised","type":"LATENT","links":null},{"name":"sde_noise","type":"LATENT","links":null}],"properties":{"Node name for S&R":"ClownsharKSampler"},"widgets_values":["gaussian","gaussian","lorentzian",0.5,7,"fixed","standard","res_2m","gauss-legendre_2s","beta57",40,0,1,1,1,"1.35",0.85]},{"id":342,"type":"FluxLoader","pos":[-370,260],"size":[340,282],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"MODEL","links":[1322],"slot_index":0},{"name":"clip","type":"CLIP","links":[1291,1323],"slot_index":1},{"name":"vae","type":"VAE","links":[1280],"slot_index":2},{"name":"clip_vision","type":"CLIP_VISION","links":[],"slot_index":3},{"name":"style_model","type":"STYLE_MODEL","links":[],"slot_index":4}],"properties":{"Node name for S&R":"FluxLoader"},"widgets_values":["flux1-dev.safetensors","fp8_e4m3fn_fast","t5xxl_fp16.safetensors","clip_l.safetensors","ae.safetensors","sigclip_vision_patch14_384.safetensors","flux1-redux-dev.safetensors"]},{"id":525,"type":"LoraLoader","pos":[-11,256],"size":[210,126],"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1322},{"name":"clip","type":"CLIP","link":1323}],"outputs":[{"name":"MODEL","type":"MODEL","links":[1324],"slot_index":0},{"name":"CLIP","type":"CLIP","links":null}],"properties":{"Node name for S&R":"LoraLoader"},"widgets_values":["FLUX 1\\RM_Illustrify_v1.0M.safetensors",1,0]}],"links":[[594,285,0,284,0,"IMAGE"],[1268,508,0,285,0,"LATENT"],[1280,342,2,285,1,"VAE"],[1291,342,1,514,0,"CLIP"],[1299,514,0,518,0,"CONDITIONING"],[1300,518,0,508,1,"CONDITIONING"],[1321,524,0,508,4,"LATENT"],[1322,342,0,525,0,"MODEL"],[1323,342,1,525,1,"CLIP"],[1324,525,0,508,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.620921323059155,"offset":[997.1131565430957,511.3482752914483]},"groupNodes":{},"ue_links":[]},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by InspectaGadget** [comment]
Auto answer : 

With a kind help of Clownshark Batwing i figured that this issue "RuntimeError: Input type (double) and bias type (float) should be the same" was about a TAESD preview setting.

**With a Latent2RGB preview setting things are just working normally.**

Close issue
